# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2018-02-10 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0030_events_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heading_Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=300)),
            ],
        ),
    ]
