# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2018-02-16 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0033_auto_20180216_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secretarie',
            name='fb_link',
            field=models.URLField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='secretarie',
            name='git_link',
            field=models.URLField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='secretarie',
            name='linkedin_link',
            field=models.URLField(max_length=50, null=True),
        ),
    ]
