# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2018-02-17 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0035_auto_20180217_0042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Head',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('department', models.CharField(choices=[('1st', 'Technical'), ('2nd', 'Event-Management'), ('3rd', 'Creativity'), ('4th', 'Publicity')], default='4th', max_length=50)),
                ('post', models.CharField(choices=[('1st', 'HEAD'), ('2nd', 'VICE-HEAD')], default='2nd', max_length=50)),
                ('Image', models.FileField(blank=True, upload_to='')),
            ],
        ),
    ]
