# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2018-02-17 11:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0036_head'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Head',
            new_name='Head_Team',
        ),
    ]
