# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2018-02-17 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0037_auto_20180217_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secretarie',
            name='Image',
            field=models.FileField(upload_to=''),
        ),
    ]
