# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2018-03-08 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import src.models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0038_auto_20180217_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.FileField(blank=True, upload_to='', validators=[src.models.validate_image]),
        ),
    ]
