# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2018-03-08 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0039_auto_20180308_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
