# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2018-03-20 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0040_auto_20180308_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='source_link',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
