# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2018-03-20 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0041_post_source_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Author',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
