# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2018-03-20 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0043_auto_20180321_0400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='name',
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
