# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2018-03-21 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0044_auto_20180321_0403'),
    ]

    operations = [
        migrations.CreateModel(
            name='event_registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('contact', models.CharField(blank=True, max_length=200)),
                ('year', models.CharField(blank=True, max_length=200)),
                ('a', models.BooleanField(default=False)),
                ('b', models.BooleanField(default=False)),
                ('c', models.BooleanField(default=False)),
                ('d', models.BooleanField(default=False)),
                ('e', models.BooleanField(default=False)),
            ],
        ),
    ]
