# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2018-03-23 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0045_event_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='rumble_event',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rumble_event',
            name='date',
            field=models.DateField(),
        ),
    ]
