# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2018-03-23 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0046_auto_20180323_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rumble_event',
            name='time',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
