# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2018-03-23 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0047_auto_20180323_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='rumble_event',
            name='Venue',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
