# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2018-03-23 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0048_rumble_event_venue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rumble_event',
            old_name='Venue',
            new_name='venue',
        ),
    ]
