# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2018-03-24 21:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0049_auto_20180323_2029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event_registration',
            old_name='a',
            new_name='tech_quiz',
        ),
    ]
