# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2018-08-09 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0051_auto_20180325_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_us',
            name='Img',
            field=models.ImageField(blank=True, null=True, upload_to='about-us'),
        ),
        migrations.AlterField(
            model_name='events',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='event-logo'),
        ),
        migrations.AlterField(
            model_name='head_team',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='team-heads'),
        ),
        migrations.AlterField(
            model_name='index_gallery',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery-index'),
        ),
        migrations.AlterField(
            model_name='inspirus_event',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='event-inpirus'),
        ),
        migrations.AlterField(
            model_name='inspirusus_gallery',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='inspirus'),
        ),
        migrations.AlterField(
            model_name='msweek_event',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='event-msweek'),
        ),
        migrations.AlterField(
            model_name='msweek_gallery',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='ms-week'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post'),
        ),
        migrations.AlterField(
            model_name='rumble_event',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='event-rumble'),
        ),
        migrations.AlterField(
            model_name='rumble_gallery',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='rumble'),
        ),
        migrations.AlterField(
            model_name='secretarie',
            name='Image',
            field=models.ImageField(upload_to='secretaries'),
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='team'),
        ),
    ]
