# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-09 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0055_auto_20180809_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='head_team',
            name='department',
            field=models.CharField(choices=[('1st', 'Technical'), ('2nd', 'Event Strategy and Planning'), ('3rd', 'Design and UX'), ('4th', 'Marketing and Communications'), ('5th', 'Social and Web Management')], default='4th', max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='department',
            field=models.CharField(choices=[('1st', 'Technical'), ('2nd', 'Event Strategy and Planning'), ('3rd', 'Design and UX'), ('4th', 'Marketing and Communications'), ('5th', 'Social and Web Management')], default='4th', max_length=50),
        ),
    ]
