# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-17 16:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0056_auto_20180809_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_registration',
            name='c',
        ),
        migrations.RemoveField(
            model_name='event_registration',
            name='d',
        ),
        migrations.RemoveField(
            model_name='event_registration',
            name='e',
        ),
    ]
