# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-19 19:53
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0057_auto_20180817_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='type',
        ),
        migrations.AddField(
            model_name='events',
            name='url',
            field=models.TextField(default='#', validators=[django.core.validators.URLValidator()]),
        ),
    ]
