# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-19 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0058_auto_20180820_0123'),
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('roll_number', models.CharField(blank=True, max_length=12)),
                ('contact', models.CharField(blank=True, max_length=200)),
                ('year', models.CharField(blank=True, max_length=200)),
                ('a', models.BooleanField(default=False)),
                ('b', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='events',
            name='url',
        ),
        migrations.AddField(
            model_name='events',
            name='type',
            field=models.CharField(choices=[('msweek', 'MS Week'), ('inspirus', 'Inspirus'), ('rumble', 'Rumble')], default='msweek', max_length=50),
        ),
    ]
