# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-20 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0063_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_registration',
            name='contact',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='event_registration',
            name='email',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='event_registration',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='event_registration',
            name='year',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='registration',
            name='contact',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='registration',
            name='roll_number',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='registration',
            name='year',
            field=models.CharField(max_length=2),
        ),
    ]
