# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-21 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0067_contact_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='url',
            field=models.CharField(default='#', max_length=200),
        ),
    ]
