# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-21 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0068_events_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='type',
        ),
        migrations.RemoveField(
            model_name='events',
            name='url',
        ),
    ]
