# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-21 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0069_auto_20180821_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='type',
            field=models.CharField(choices=[('msweek', 'MS Week'), ('inspirus', 'Inspirus'), ('rumble', 'Rumble')], default='msweek', max_length=50),
        ),
        migrations.AddField(
            model_name='events',
            name='url',
            field=models.CharField(default='#', max_length=200),
        ),
    ]
