# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-12 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0070_auto_20180821_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='department',
            field=models.CharField(choices=[('1st', 'Technical'), ('2nd', 'Event Strategy and Planning'), ('3rd', 'Design and UX'), ('4th', 'Marketing and Communications')], default='4th', max_length=50),
        ),
    ]
