# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-20 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0071_auto_20180913_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heading_content',
            name='content',
            field=models.TextField(max_length=600),
        ),
    ]
