# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-09 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0073_hkct_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='hkct_ouside',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('contact', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('institute', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
